# baseURL: "https://ossig.netlify.com/"
disableKinds: ["taxonomy", "taxonomyTerm"]
languageCode: en-us
title: OHBM Open Science SIG
theme: hugo-fresh

params:
  navbarlogo:
  # Logo (from /images/logos/___)
   image: logos/ossig_logo.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: The OHBM Open Science Special Interest Group
    # Hero subtitle (optional)
    subtitle: Dedicated to promoting and supporting open science within our community
    # Button text
    buttontext: Learn more
    # Where the main hero button links to
    buttonlink: "#openumbrella"
    # Hero image (from /images/___)
    image: illustrations/undraw_scrum_board.svg

  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Our Team
    url: "/#OSSIG_team"
  - title: Hackathon
    url: "/hackathon"
  - title: Awards
    url: "/awards"
  - title: Open Science Room
    url: "/osr"
  - title: Sponsors
    url: "/sponsors"
  # - title: Election Bylaws
  #   url: https://docs.google.com/document/d/176tTI7eLIxZkvTL8vhnM7maoCJFhLVaAgwywDnWfONo/edit?usp=sharing
  # - title: Join the OSSIG
  #   url: https://docs.google.com/forms/d/e/1FAIpQLSehJ6T9LHRhwJwyvUXJ3R9mVw6OUztdei63YJofUtL2DO35ng/viewform?usp=sf_link

  hackathon:
    title: Save the date
    subtitle: It is coming... Finally.
    id: hackathon
    image: illustrations/landing_hackathon_2020.jpg
    buttonText: More info here
    buttonLink: https://github.com/ohbm/hackathon2020/blob/master/README.md

  team:
    title: Our team
    subtitle: The people behind the OSSIG
    id: OSSIG_team
    # images (from /images/faces/2020/___.jpg)
    members:
      # chair, secretary, treasurer
    - name: Camille Maumet
      role: Chair
      image: camille_maumet
      affiliation: Inria, Univ Rennes, CNRS, Inserm
      twitter: https://twitter.com/cmaumet
    - name: Ana Van Gulick
      role: Secretary
      image: ana_van_gulick
      affiliation: Figshare; Carnegie Mellon University, University Libraries and Department of Psychology
      twitter: https://twitter.com/anavangulick
    - name: Eugene Duff
      role: Treasurer
      image: eugene_duff
      affiliation: University of Oxford, Department of Pediatrics
      twitter: https://twitter.com/EugenePDuff

      # elect chair, secretary, treasurer
    - name: Aki Nikolaidis
      role: Chair Elect
      image: aki_nikolaidis
      affiliation: Child Mind Institute
      twitter: https://twitter.com/AkiNikolaidis
    - name: Katie Bottenhorn
      role: Secretary Elect
      image: katie_bottenhorn
      affiliation: Florida International University, Department of Psychology
      twitter: https://twitter.com/62442katieb
    - name: Tristan Glatard
      role: Treasurer Elect
      image: tristan_glatard
      affiliation: Concordia University, Department of Computer Science and Software Engineering
      twitter: https://twitter.com/TristanGlatard

      # hackathon
    - name: Rémi Gau
      role: Hackathon co-chair
      image: remi_gau
      affiliation: Institute of Psychology, Université Catholique de Louvain
      twitter: https://twitter.com/RemiGau
    - name: Liza Levitis
      role: Hackathon co-chair
      image: liza_levitis
      affiliation: Montreal Neurological Institute, McGill University
      twitter: https://www.twitter.com/LevitisLiza

      # OSR
    - name: Cassandra Gould van Praag
      role: Open Science Room Co-Chair
      image: cass_gvp
      affiliation: University of Oxford, Department of Psychiatry
      twitter: https://twitter.com/cassgvp
    - name: Stephan Heunis
      role: Open Science Room Co-Chair
      image: stephan_heunis
      affiliation: Eindhoven University of Technology, Department of Electrical Engineering
      twitter: https://twitter.com/fmrwhy

      # past chair, secretary, treasurer
    - name: Kirstie Whitaker
      role: Past Chair
      image: kirstie_whitaker
      affiliation: Alan Turing Institute and University of Cambridge
      twitter: https://twitter.com/kirstie_j
    - name: Elizabeth DuPre
      role: Past Secretary
      image: elisabeth_dupre
      affiliation: Montreal Neurological Institute, McGill University
      twitter: https://twitter.com/emdupre_
    - name: Greg Kiar
      role: Past Treasurer
      image: greg_kiar
      affiliation: Montreal Neurological Institute, McGill University
      twitter: https://twitter.com/g_kiar

      # liaison
    - name: Thomas Nichols
      role: Council Liaison
      image: tom_nichols
      affiliation: University of Oxford, Nuffield Department of Population Health
      twitter: https://twitter.com/ten_photos

  sponsors:
    title: Our sponsors
    subtitle: We are grateful for the generous support of our sponsors
    titleopp: Sponsorship opportunities
    tiersimage: /images/illustrations/ossig_sponsorship_tiers.jpg
    subtitleopp: Interested in supporting us? Please see our sponsorship opportunities below!
    sponsors:
    - name: Open science champions
      oursponsors:
        - name: "Openneuro"
          image: /images/logos/openneuro_logo.png
          url: https://openneuro.org/
    - name: Hackathon champions
      oursponsors:
        - name: "INCF"
          image: /images/logos/incf_logo.png
          url: https://www.incf.org/
        - name: "Courtois NeuroMod"
          image: /images/logos/cneuromod_logo.svg
          url: https://www.cneuromod.ca/
          height: 5em
        - name: "CONP"
          image: /images/logos/conp_logo.png
          url: https://conp.ca/
    - name: Hackathon supporters
      oursponsors:
        - name: "WIN"
          image: /images/logos/logo_WIN_clear.png
          url: https://www.win.ox.ac.uk/
        - name: "UNIQUE"
          image: /images/logos/Unique_logo.png
          url: http://unique.quebec
    #     - name: "Child Mind Institute"
    #       # image: /images/logos/child-mind-institute_logo.png
    #       url: https://childmind.org/
    #     - name: "Ludmer Centre"
    #       # image: /images/logos/ludmer_logo.png
    #       url: http://ludmercentre.ca/
    # - name: Open Science Room supporter
    #   oursponsors:
    - name: Sponsors
      oursponsors:
        - name: "OHBM Australian chapter"
          image: "/images/logos/OHBM_australian_chapter.png"
          url: "https://ohbmaustralia.wordpress.com/"

  section2:
    title: Open science is an umbrella.
    subtitle: We're here to help grow the community supporting it.
    id: openumbrella
    features:
    - title: Open data
      text: Sharing neuroimaging data isn't easy, but we can make it easier. We're interested in understanding how OHBM members share data, where they encounter difficulties, and what kinds of new infrastruce and ethics can make next-generation data-sharing possible.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: mouse-globe
    - title: Open code
      text: Analysis code is often a second-class citizen in neuroimaging research, but we can change that. We help to teach scientists best-practices in software development—and how those practices can result in real-world gains in research quality and output.
      icon: laptop-cloud
    - title: Open publishing
      text: Papers shouldn't hide behind paywalls. We want to help create solutions to enable new, open-acess platforms and to facilitate free information.
      icon: doc-sync

  footer:
    # Logo (from /images/logos/___)
    logo: ossig_logo.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/OHBM
      # Icons are from Font Awesome
      icon: github
    - link: https://twitter.com/ohbmopen
      icon: twitter
    bulmalogo: false
